version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/apps/desktop/src-tauri"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "glib"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
